import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { lazy } from "react";
import Providers from "@/redux/Provider";
import { ColorContextProvider } from "@/theme/MUI_MODE";
import DashboardLayout from "@/components/secure/Layout";

export const metadata: Metadata = {
  title: "Aryanakala | آریاناکالا",
  description: "Generated by create next app",
  icons: "/favicon.png",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {" "}
        <ColorContextProvider>
          <Toaster richColors position="bottom-left" />
          <Providers>
            <DashboardLayout>{children}</DashboardLayout>
          </Providers>
        </ColorContextProvider>
      </body>
    </html>
  );
}
